//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace log4net.Appender.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("log4net.Appender.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password property not defined in appender/config: &lt;Password value=&apos;zendeskapitoken&apos; /&gt;.
        /// </summary>
        internal static string PasswordPropertyNotDefined {
            get {
                return ResourceManager.GetString("PasswordPropertyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequesterId property not defined in appender/config: &lt;RequesterId value=&apos;RequesterId(#)&apos; /&gt; Example: &lt;RequesterId value=&apos;1&apos; /&gt;.
        /// </summary>
        internal static string RequesterIdPropertyNotDefined {
            get {
                return ResourceManager.GetString("RequesterIdPropertyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags property not defined in appender/config: &lt;Tags value=&apos;log4net tags to set&apos; /&gt;.
        /// </summary>
        internal static string TagsPropertyNotDefined {
            get {
                return ResourceManager.GetString("TagsPropertyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url property not defined in appender/config: &lt;Url value=&apos;https://zendeskurl.zendesk.com&apos;&gt;.
        /// </summary>
        internal static string UrlPropertyNotDefined {
            get {
                return ResourceManager.GetString("UrlPropertyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User property not defined in appender/config: &lt;User value=&apos;zendeskusername/token&apos; /&gt;.
        /// </summary>
        internal static string UserPropertyNotDefined {
            get {
                return ResourceManager.GetString("UserPropertyNotDefined", resourceCulture);
            }
        }
    }
}
